<?php

/**
 * @file
 * Contains migrate_custom.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function migrate_custom_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the migrate_custom module.
    case 'help.page.migrate_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom migration module for migraregresoacasa.mx userdata') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function migrate_custom_theme()
{
  $theme = [];

  return $theme;
}

/**
 * Implements hook_uninstall().
 *
 * Cleans up config entities installed by this module.
 */
function migrate_custom_uninstall() {
  db_query("DELETE FROM {config} WHERE name LIKE 'migrate.migration.custom%'");
  drupal_flush_all_caches();
}

